# version: "3.9"

# services:
#   auth_service:
#     build:
#       context: ../services/auth_service
#     container_name: auth_service
#     working_dir: /app/app
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ../services/auth_service:/app
#     ports:
#       - "8000:8000"
#     env_file:
#       - ../services/auth_service/.env
#     depends_on:
#       auth_migration:
#         condition: service_completed_successfully

#     product_service:
#       build:
#         context: ../services/product_service
#       container_name: product_service
#       working_dir: /app/app  
#       command: python manage.py runserver 0.0.0.0:8001
#       volumes:
#       - ../services/product_service:/app
#       ports:
#       - "8001:8001"
#       env_file:
#       - ../services/product_service/.env
#       depends_on:
#       - product_db

#   # --- New Migration Service ---
#   auth_migration:
#     build:
#       context: ../services/auth_service
#     container_name: auth_migration
#     working_dir: /app/app
#     # This command runs migrations and exits
#     command: >
#       sh -c "python manage.py makemigrations && 
#              python manage.py migrate"
#     volumes:
#       - ../services/auth_service:/app
#     env_file:
#       - ../services/auth_service/.env
#     depends_on:
#       - db

#   auth_db:
#     image: postgres:15
#     container_name: auth_db
#     environment:
#       POSTGRES_DB: auth_db
#       POSTGRES_USER: auth_user
#       POSTGRES_PASSWORD: auth_password
#     ports:
#       - "5432:5432"
#     volumes:
#       - auth_postgres_data:/var/lib/postgresql/data

#   product_db:
#     image: postgres:15
#     environment:
#       POSTGRES_DB: product_db
#       POSTGRES_USER: product_user
#       POSTGRES_PASSWORD: product_password
#     volumes:
#     - product_postgres_data:/var/lib/postgresql/data

# volumes:
#   auth_postgres_data:

# version: "3.9"

services:
  auth_service:
    build:
      context: ../services/auth_service
    working_dir: /app/app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../services/auth_service:/app
    ports:
      - "8000:8000"
    env_file:
      - ../services/auth_service/.env
    depends_on:
      - auth_db

  auth_db:
    image: postgres:15
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  product_service:
    build:
      context: ../services/product_service
    working_dir: /app/app
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ../services/product_service:/app
    ports:
      - "8001:8001"
    env_file:
      - ../services/product_service/.env
    depends_on:
      - product_db

  product_db:
    image: postgres:15
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: product_user
      POSTGRES_PASSWORD: product_password
    volumes:
      - product_postgres_data:/var/lib/postgresql/data

  cart_service:
    build:
      context: ../services/cart_service
    working_dir: /app/app
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - ../services/cart_service:/app
    ports:
      - "8002:8002"
    env_file:
      - ../services/cart_service/.env
    depends_on:
      - cart_db

  cart_db:
    image: postgres:15
    environment:
      POSTGRES_DB: cart_db
      POSTGRES_USER: cart_user
      POSTGRES_PASSWORD: cart_password
    volumes:
      - cart_postgres_data:/var/lib/postgresql/data
      
  order_service:
    build:
      context: ../services/order_service
    working_dir: /app/app
    command: python manage.py runserver 0.0.0.0:8003
    volumes:
      - ../services/order_service:/app
    ports:
      - "8003:8003"
    env_file:
      - ../services/order_service/.env
    depends_on:
      - order_db

  order_db:
    image: postgres:15
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: order_password
    volumes:
      - order_postgres_data:/var/lib/postgresql/data

volumes:
  auth_postgres_data:
  product_postgres_data:
  cart_postgres_data:
  order_postgres_data: